### ISSUE TITLE
Multiple Defintions error

### ISSUE THREAD

**Issue by Szum123321** [khoih-prog/TimerInterrupt_Generic#3] opened 2021-04-22 19:14 UTC
Hi!

I'm trying to compile some code for Teensy 3.5 with PlatformIO  2.3.2, and I'm getting multiple definitions error.

I followed the procedure described in README, which sadly didn't work even though I cleaned the build environment and restarted VScode all the time.

Error message looks like this: [link](https://pastebin.com/1ityGyLZ)

I'm using Arch based linux distro:
Linux sz-81nh 5.11.14-arch1-1 #1 SMP PREEMPT Wed, 14 Apr 2021 12:06:34 +0000 x86_64 GNU/Linux

Also, the same code (the only difference being instead of TeensyTimer, I used STM32Timer) compiles and works perfectly on ST Nulceo F303RE

### Steps to Reproduce
Minimal example: [Teensy_minimal.zip](https://github.com/khoih-prog/TimerInterrupt_Generic/files/6360680/Teensy_minimal.zip)

### Expected behavior

Code compiles for Teensy

### Actual behavior
Linker spews out a bunch of `Multiple definitions error`

**Comment by khoih-prog** [comment] 2021-04-22 20:02
I don't see you use this library anywhere in the code.

It seems that you're using `TeensyTimers` library and there is something wrong with it and PIO.

I'm closing the issue now as invalid, until you prove that the issue is caused by this library.

**Closed as completed by khoih-prog** 2021-04-22 20:02 UTC
Labels: Support

**Comment by Szum123321** [comment] 2021-04-23 06:01
The library is included in include/I2CEEPROM.h file

**Comment by khoih-prog** [comment] 2021-04-23 06:32
You have to modify your code as follows

1. main.cpp

```
#include <Arduino.h>
#include "TimerInterrupt_Generic.h"
#include "I2CEEPROM.h"

I2CEEPROM mem;

void setup() 
{
}

void loop() 
{
}
```

---

2. I2CEEPROM.h

```
#include <Arduino.h>
#include <Wire.h>
#include <math.h>

#ifdef __STM32__
  STM32Timer DEVICE_TICK_TIMER(TIM2);
#elif defined(__TEENSY__)
  TeensyTimer DEVICE_TICK_TIMER(TEENSY_TIMER_3);
#endif

#ifndef I2CEEPROM_H
#define I2CEEPROM_H

//#define __STM32__
#define __TEENSY__

class I2CEEPROM {};

#endif
```

---

3. I2CEEPROM.cpp

```
#include "I2CEEPROM.h"

/*library code here*/
```
---

Compile will be OK as tested on Arduino IDE, unless your PIO settings /configuration are wrong

![Selection_744](https://user-images.githubusercontent.com/57012152/115828664-03fd5a00-a3dc-11eb-89a6-5576688beea8.png)

**Comment by khoih-prog** [comment] 2021-04-23 06:51
You have to modify like this to use new C++ style hpp

1. main.cpp or Teensy_minimal.ino

```
#include <Arduino.h>
#include "I2CEEPROM.h"

I2CEEPROM mem;

void setup() 
{
}

void loop() 
{
}
```

---

2. I2CEEPROM.h

```
#ifndef I2CEEPROM_H
#define I2CEEPROM_H

#include <Arduino.h>
#include <Wire.h>
#include <math.h>
#include "TimerInterrupt_Generic.h"

class I2CEEPROM {};

#include "I2CEEPROM_Impl.hpp"

#endif
```

---

3. I2CEEPROM_Impl.hpp


```
#ifndef I2CEEPROM_IMPL_HPP
#define I2CEEPROM_IMPL_HPP

#if ( defined(STM32F0) || defined(STM32F1) || defined(STM32F2) || defined(STM32F3)  ||defined(STM32F4) || defined(STM32F7) || \
       defined(STM32L0) || defined(STM32L1) || defined(STM32L4) || defined(STM32H7)  ||defined(STM32G0) || defined(STM32G4) || \
       defined(STM32WB) || defined(STM32MP1) )
  STM32Timer DEVICE_TICK_TIMER(TIM2);
#elif ( defined(CORE_TEENSY) || defined(TEENSYDUINO) )
  TeensyTimer DEVICE_TICK_TIMER(TEENSY_TIMER_3);
#endif

/*library code here*/

#endif    // I2CEEPROM_IMPL_HPP
```
---

Compile is OK on Arduino IDE, and should be OK on PIO, unless you have wrong settings / configurations

![Selection_746](https://user-images.githubusercontent.com/57012152/115831404-8a676b00-a3df-11eb-93c7-ac997ca16486.png)
